# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:    
      - '**hoge-[0-9]+**'

jobs:
  pr-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          cat << EOF > comments
          ちゃんと投稿された？
          - [ ] された
          EOF
          
      - name: Post　comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comments "${URL}"
