# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened

jobs:
  pr-comment:
    if: startsWith(github.head_ref, 'feature/hoge-') || startsWith(github.head_ref, 'hoge-')
    runs-on: ubuntu-latest

    steps:
      - name: Create Comment file
        run: |
          cat << EOF > comment
          ちゃんと投稿された？
          - [ ] された
          EOF
          
      - name: Post　comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comment "${URL}"
