name: CI

on:
  push:
    branches:
      - 'feature/hoge-[0-9]+**'
      - 'hoge-[0-9]+**'

jobs:
  pr-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Create Comment file
        run: |
          cat << EOF > comment
          @${{ github.event.sender.login }}
          ちゃんと投稿された？
          - [ ] された
          EOF
          
      - name: Post　comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comment "${URL}"
